assets/index/Select.less, src/module/Select.jsx
隐藏滚动条，当 hover 到浮层上是出现，以提升视觉体验。
=> Feature hide scrollbar

src/module/Panel.jsx
SCRIPT5028: Function.prototype.apply: 缺少 Array 或 arguments 对象
=> SCRIPT5028: Function.prototype.apply: 缺少 Array 或 arguments 对象

src/Panel.jsx
=> chore: add className for Panel

README.md, examples/format.js, src/Combobox.jsx, src/Panel.jsx, src/TimePicker.jsx
https://github.com/ant-design/ant-design/issues/3793#issuecomment-259877163
=> Feat show minute

README.md, src/TimePicker.jsx
Allow setting a prop to name the generated input field.
=> Add prop for naming the input

package.json, src/TimePicker.jsx
ref: https://github.com/ant-design/ant-design/issues/3790
=> feat: support .focus

src/Combobox.jsx, tests/TimePicker.spec.jsx
Plus added one more test for that
=> Fixed unwanted exception if value is undefined

.gitignore, package.json
ref: https://github.com/react-component/react-component.github.io/issues/12
=> feat: expose es files

src/TimePicker.jsx, tests/TimePicker.spec.jsx
Hey folks,
tried to implement focus/blur support complete with it's own test.
Let me know if it fits your standards.
Greetings,
Christian
=> add focus/blur support.

src/Header.jsx, src/Panel.jsx, src/TimePicker.jsx
- It will be useful if we want to detect Enter or any other keycode on Header input
=> Add keydown function on header input

assets/index/Select.less
=> Fix Select max-height and overflow

README.md, examples/open.js, src/Header.jsx, src/Panel.jsx, src/TimePicker.jsx, tests/Header.spec.jsx
focuses the input when the picker opens if focusOnOpen option is set
=> add focusOnOpen option (#61)

src/Combobox.jsx, tests/Select.spec.jsx
This PR fixes disabled hours for 12 hour picker dropdown.
=> Fixes #75: Disabled Hours for 12 hour picker

README.md, src/TimePicker.jsx
Added an id prop to the input element
=> Add id to input element

README.md
=> Fixed small typo in Readme

README.md
Remove documented parameter options for placement that do not actually work/exist in the code.
=> Issue #124. Remove documented parameters that are not usable

.travis.yml, HISTORY.md, examples/open.js, examples/value-and-defaultValue.js, package.json, src/Combobox.jsx, src/Header.jsx, src/Panel.jsx, src/Select.jsx, src/TimePicker.jsx, tests/Header.spec.jsx, tests/Select.spec.jsx, tests/TimePicker.spec.jsx, tests/index.js, tests/setup.ts, tests/util.js
https://github.com/react-component/rc-tools/pull/61#pullrequestreview-187612243
=> Upgrade rc tools 9

src/Select.jsx
Allow popup list items to be selected with the keyboard
similar goal as https://github.com/react-component/time-picker/pull/83
=> feat: Accessibility Updates

src/Combobox.jsx, src/Panel.jsx, src/Select.jsx, tests/Select.spec.jsx, tests/util.js
=> feat: Accessibility - Escape should close popup

README.md
https://github.com/react-component/time-picker/issues/125#issuecomment-512296669
=> Add required CSS import to README

package.json, src/Header.jsx, src/Panel.jsx, src/TimePicker.jsx
https://github.com/ant-design/ant-design/issues/9792
=> Migrate to new lifecycle

index.d.ts
Because it was missing in type definition.
Also I would really like a Hacktoberfest 👕. Highly appreciated if you could merge it before end of the month 😍
=> added popupStyle to typings

index.d.ts
Adds
* `autoComplete`
* `onFocus`
* `onBlur`
* `autoFocus`
---
Please update 3.x as well 🙏
=> Type fixes: add missing props

index.d.ts
Edited props that fix the dropdown on scroll issue.
=> Edit Types to be optional
